version: '3'

services:
  app:
    build: ./REST-API
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq

  #chat:
    #build: ./WebSocket-service
    #restart: always
    #ports:
    #  - 3001:3001

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpass
    